[project]
name = "common"
version = "{{cookiecutter.version}}"
description = "Funções comuns a todos os pacotes do projeto"
readme = "README.md"
authors = [
    { name = "{{cookiecutter.full_name}}", email = "{{cookiecutter.email}}" }
]
requires-python = ">={{cookiecutter.python_version}}"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
