[project]
name = "src"
version = "{{cookiecutter.version}}"
description = "Código fonte do projeto"
readme = "README.md"
authors = [
    { name = "{{cookiecutter.full_name}}", email = "{{cookiecutter.email}}" }
]
requires-python = ">={{cookiecutter.python_version}}"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
